### ISSUE TITLE
Open app in separate window

### ISSUE THREAD

**Issue by psonawane-servicetitan** [lampaa/com.lampa.startapp#103]
Is there a way to open app in independent window? Currently it is opening new app as a nested part of old app. Also, if the app is opened in background, it should resume it in foreground.

One more thing, does this plugin allow to check if external app is installed or not?

**Comment by lampaa** [comment]
Hi!

> Is there a way to open app in independent window? Currently it is opening new app as a nested part of old app. Also, if the app is opened in background, it should resume it in foreground.

Hmm, i honestly do not know.

> One more thing, does this plugin allow to check if external app is installed or not?

For check app is installed use this code:

```js
var sApp = startApp.set({ /* params */
	"action":"ACTION_MAIN",
	"category":"CATEGORY_DEFAULT",
	"type":"text/css",
	"package":"com.lampa.startapp",
	"uri":"file://data/index.html",
	"flags":["FLAG_ACTIVITY_CLEAR_TOP","FLAG_ACTIVITY_CLEAR_TASK"],
	"component": ["com.app.name","com.app.name.Activity"],
	"intentstart":"startActivity",
}, { /* extras */
	"EXTRA_STREAM":"extraValue1",
	"extraKey2":"extraValue2"
});

sApp.check(function(values) { /* success */
	console.log(values);
}, function(error) { /* fail */
	alert(error);
});
```

**Comment by psonawane-servicetitan** [comment]
Ok. Thanks for the info.

**Comment by MaxNgai** [comment]
> external

So now is still impossible to open a son application in a new window rather than covering the old one?
