### ISSUE TITLE
Problem with Phonegap build

### ISSUE THREAD

**Issue by nrtlourenco** [lampaa/com.lampa.startapp#105]
Hello,
I am having (recently) the following problem with Adobe Phonegap build:

`Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: startApp.java`

Log:
```
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/com/lampa/startapp/startApp.java:167: error: cannot find symbol
								uri = FileProvider.getUriForFile(this.cordova.getContext(), "com.lampa.startapp.fileProvider", new File(new URI(uri_str)));
								                                             ^
  symbol:   method getContext()
  location: variable cordova of type CordovaInterface

```

Can someone help me with this?
(I am temporarily using #3116a13 to be able to build, so it's related to the Android N Support commit AFAIK)

Thank you!

**Comment by lampaa** [comment]
Hi!

Oy, i fixed this problem today or tomorrow.

**Comment by lampaa** [comment]
Fixed.
