### ISSUE TITLE
Open dropbox app with a specified path

### ISSUE THREAD

**Issue by kyblinh** [lampaa/com.lampa.startapp#106]
Hello, 
We are trying to open dropbox app in a specified folder. It's quite easy to find how to open just dropbox, but can't find how i can give the path...
I 'd guess code would be something like 
```js
var sApp = startApp.set({
    "application": "com.dropbox.android",
    "uri": attachmentLink,
    "action": "ACTION_VIEW"
}).start();
```

Is there any way to do it?

Thanks for your great plugging :)

**Comment by lampaa** [comment]
Hi, @kyblinh 
This can not be done through by intent.
