### ISSUE TITLE
Error build Android platform

### ISSUE THREAD

**Issue by hatsantos** [lampaa/com.lampa.startapp#111]
I'm getting an error when build/run the Android platform.

I get his error:

```
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
**D:\_GIT\AppStarterDemo\platforms\android\src\com\lampa\startapp\startApp.java:41: error: strings in switch are not supported in -source 1.6
                switch (action) {
                       ^
  (use -source 7 or higher to enable strings in switch)
D:\_GIT\AppMunicipios\platforms\android\src\com\lampa\startapp\startApp.java:105: error: cannot find symbol
                        cordova.getContext().registerReceiver(receiver, filter);
                               ^
  symbol:   method getContext()
  location: variable cordova of type CordovaInterface**
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**System information**
Node version: v8.11.2
Cordova version: 7.1.0
Cordova Android: 6.3.0
Plugin Version: 0.1.5

**Comment by lampaa** [comment]
Hi!
What is your version of java? 1.6? 
Please, update java to 1.8.

**Comment by hatsantos** [comment]
Hello @lampaa,
Thank you for your reply.

I think I'm using the lates version.

```
d:\_GIT\AppStarterDemo>**java -version**
Picked up _JAVA_OPTIONS: -Xmx1g
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) Client VM (build 25.172-b11, mixed mode, sharing)
```

**Comment by lampaa** [comment]
go to platforms/android/CordovaLib/build.gradle

and find 

```
android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

and find this code in other gradle files and change version to `VERSION_1_8`

**Comment by lampaa** [comment]
For fix `cordova.getContext()` please replace `cordova.getContext()` to `cordova.getActivity().getApplicationContext()` in file `platforms/android/app/src/main/java/com/lampa/startapp/startApp.java:105`

**Comment by nawirulfadly** [comment]
Hay @lampaa 
Thanks For Replay, I'm getting an same error, and solve with version_1_8 and cordova.getActivity().

but I'm build/run again, I get his error:
```
 \platforms\android\src\com\lampa\startapp\startApp.java:93: error: local variable callback is accessed from within inner class; needs to be declared final

                                callback.sendPluginResult(pluginResult);
                                ^
\platforms\android\src\com\lampa\startapp\startApp.java:312: error: local variable PackInfo is accessed from within inner class; needs to be declared final
                                                put("versionName", PackInfo.versionName);
                                                                   ^
\platforms\android\src\com\lampa\startapp\startApp.java:313: error: local variable PackInfo is accessed from within inner class; needs to be declared final
                                                put("packageName", PackInfo.packageName);
                                                                   ^
\platforms\android\src\com\lampa\startapp\startApp.java:314: error: local variable PackInfo is accessed from within inner class; needs to be declared final
                                                put("versionCode", PackInfo.versionCode);
                                                                   ^
\platforms\android\src\com\lampa\startapp\startApp.java:315: error: local variable PackInfo is accessed from within inner class; needs to be declared final
                                                put("applicationInfo", PackInfo.applicationInfo);
```
any solution?
Thanks

**Comment by lampaa** [comment]
Amazing 💃 

I fixed this bugs in 6.1.3 version. Update plugin in you project or add changes to file `platforms/android/app/src/main/java/com/lampa/startapp/startApp.java`

310 line: add `final`:
```js
final PackageInfo PackInfo = pm.getPackageInfo(params.getString("package"), PackageManager.GET_ACTIVITIES);
```

and line 71 add `final`: 
```js
private void receiver(JSONArray args, final CallbackContext callback) {
```

thanks for reports

**Comment by lampaa** [comment]
@nawirulfadly i updated plugin to 6.1.4, please update in your.

**Comment by nawirulfadly** [comment]
wow Amazing,....
Thanks @lampaa  For Update solving problem,

**Comment by lampaa** [comment]
Its good. I close issue.

**Comment by Basavaraj-Tanikedar** [comment]
rror: strings in switch are not supported in -source 1.6
		switch (action) {
		       ^
  (use -source 7 or higher to enable strings in switch)
/Users/dev1/Documents/dgbeing/spacebud-app/platforms/android/src/com/lampa/startapp/startApp.java:107: error: cannot find symbol
			cordova.getContext().registerReceiver(receiver, filter);
			       ^
  symbol:   method getContext()
  location: variable cordova of type CordovaInterface
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

I added this code also 
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

and I changed this code also not working please help me
cordova.getActivity().getApplicationContext()

**Comment by lampaa** [comment]
Hi, @Basavaraj-Tanikedar 
For change java version check all config files in platform/android and then check that you have installed java 1.8.

**Comment by lampaa** [comment]
@Basavaraj-Tanikedar  or update plugin to 6.1.6
