### ISSUE TITLE
Build error startApp.java:30

### ISSUE THREAD

**Issue by liuyichuan** [lampaa/com.lampa.startapp#112]
java version on 1.8 got this error,
startApp.java:30
private HashMap<Integer, BroadcastReceiver> broadcastReceiverHashMap = new HashMap<>();

**Comment by lampaa** [comment]
Hi, @liuyichuan 
I fixed this error. Please, update plugin.

**Comment by liuyichuan** [comment]
Hi,@lampaa.
I still got this error when building on Android after update.

**Comment by lampaa** [comment]
Try to remove and re-install the plugin:

```
cordova plugin rm com.lampa.startapp
cordova plugin add com.lampa.startapp
```

**Comment by liuyichuan** [comment]
<plugin name="com.lampa.startapp" spec="^6.1.4" />
Did not code. Just install the plugin and build. Still got same error. 
I am using ionic3.

**Comment by lampaa** [comment]
@liuyichuan hmm. Delete plugin and re-install (6.1.6)
