### ISSUE TITLE
Start To Background

### ISSUE THREAD

**Issue by taufiksu** [lampaa/com.lampa.startapp#118]
How to make application when start is run to background/pause state?

**Comment by taufiksu** [comment]
I use your plugin and to start my cordova application. But i want to make my application run on background (not on the top of other application that still open) after start from when using your plugin.

**Comment by taufiksu** [comment]
i search and found to set "action":"ACTION_MAIN", "category":"CATEGORY_HOME", to make my app run not on foreground but still active on foreground not in background. can you help me?

**Comment by lampaa** [comment]
@taufiksu It's impossible. Only if the application works as a service.

**Comment by taufiksu** [comment]
I have background service plugin running, the problem is only to make the app pause after open by your plugin. Is this possible?

**Comment by lampaa** [comment]
No, its impossible.

**Comment by taufiksu** [comment]
Ok then, thankyou very much
