### ISSUE TITLE
Android intent category

### ISSUE THREAD

**Issue by tmmachado** [lampaa/com.lampa.startapp#12]
Does it support intent category? (http://developer.android.com/reference/android/content/Intent.html#CATEGORY_APP_MUSIC)
Something like: [["action", "MAIN"], ["category", "APP_MUSIC"]] //open native music app

I've tried the above but it didn't work.
I also added the following to my android manifest:
```xml
<intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.APP_MUSIC" />
</intent-filter>
```

**Comment by lampaa** [comment]
Hi, @tmmachado!
Sorry, but at the moment category is not supported.

But, see this code:
```javascript
navigator.startApp.start([["action", "MUSIC_PLAYER"]], function(a) {  
    alert(a); 
},  
function(error) {
    alert(error); 
});
```
