### ISSUE TITLE
I am Not Getting extrafields from One app to Another App

### ISSUE THREAD

**Issue by umeshShindepatil** [lampaa/com.lampa.startapp#120]
Hi @lampaa 
I am not getting extra fields in another app. below is my code -

**First App Code -** 

            var sApp = startApp.set({
                "application":"com.phonegap.test"
            }, { 
                "Serial_Number":"U0106880005"
            });

            sApp.start(function() { /* success */
                alert('ok -');                     // here i am getting ok alert after opening second app
            }, function(error) { 
                alert("error -" + error);
            }, function() {
                alert('arguments - ' + arguments);
            }); 

**Second App code -** 

            function onDeviceReady() {
            alert('ready deviceeeee');           // here i am getting ready device alert after open second app
            startApp.extraFields(function (fields) {      // here not getting fields which is passed from first app
                alert('fieldssss');
            }, function (fail) { /* fail */
                alert(fail);
            });

            var field = "extra_field";
            startApp.getExtra(field, function (value) {
                alert('valuesss');
            }, function (fail) {
                alert(fail);
            });
        }

**Config.xml added plugin in both app -** 

plugin name="https://github.com/lampaa/com.lampa.startapp.git" source="npm"

**Comment by lampaa** [comment]
Hi, @umeshShindepatil.
I will check code tomorrow.

**Comment by umeshShindepatil** [comment]
ok thank you @lampaa

**Comment by umeshShindepatil** [comment]
Hi @lampaa 
Did you get chance to check above code

**Comment by lampaa** [comment]
Hi, you made mistakes: 
rename `extraFields` to `getExtras`.
Result:

First app:
```js
var sApp = startApp.set({
    "application":"com.example.hello2"
}, {
    "Serial_Number":"U0106880005"
});

sApp.start(function() { /* success */
    console.log('ok');
}, function(error) {
    console.log("error -" + error);
}); 
```

Second app:
```
startApp.getExtras(function (fields) {
    console.log(fields);
}, function (fail) { /* fail */
    console.log(fail);
});

startApp.getExtra("Serial_Number", function (value) {
    console.log(value);
}, function (fail) {
    console.log(fail);
});
```
