### ISSUE TITLE
Android Activities are started incorrectly

### ISSUE THREAD

**Issue by Dragas** [lampaa/com.lampa.startapp#129]
When providing a single value via `intent` key, the android implementation seems to call `Intent(String)` constructor, which is equivalent to the following

```
Intent it = new Intent()
it.setAction(getParam('intent'))
```

This causes issues when trying to launch activities that are exposed by dependencies. Instead you should be simulating an `Intent(Context, Class<?>)` constructor, which does the following

```
Intent it = new Intent()
ComponentName cm = new ComponentName(this.cordova.getActivity().getPackageName, getParam('intent'))
it.setComponent(cm)
```

where intent is fully qualified class name for activity you want to open.

**Comment by lampaa** [comment]
Hello! 
Thanks for fix!
