### ISSUE TITLE
Vulnerable locations:  com.startapp.android.publish.adsCommon.adinformation.b->onClick

### ISSUE THREAD

**Issue by matrixreal** [lampaa/com.lampa.startapp#133]
hello,
i got a alert on google play they say my app wille be removed and i have to fix thi
Vulnerable locations:
com.startapp.android.publish.adsCommon.adinformation.b->onClick
thanks for help

**Comment by lampaa** [comment]
Hello, please check your code. My plugin not contains ads. View https://github.com/StartApp-SDK/Documentation/wiki/Android-InApp-Documentation
