### ISSUE TITLE
Open phone call history ?

### ISSUE THREAD

**Issue by lakano** [lampaa/com.lampa.startapp#16]
Hello,

I known it's possible to run "tel://0123456789" scheme to call the number, but I would like to only open the tel application, without any number.

The goal is to permit to the user to go quickly in his call history.

May be with your plugin we can call something like "com.apple.tel", but I don't known the exact ID to open it :-/

Thanks for your help :)

**Comment by lampaa** [comment]
Hi, @lakano!
See http://stackoverflow.com/questions/4556392/how-do-i-create-an-intent-that-opens-the-call-log-activity

```js
navigator.startApp.start([["action", "VIEW"], ["content://call_log/calls"]], ...);
```

**Comment by lakano** [comment]
Thanks @lampaa !
But this seems to be specific for Android... May be it's not possible for iOS :-/

**Comment by lampaa** [comment]
@lakano, I'm sorry, but I can not help you:
http://stackoverflow.com/questions/31002583/ios-open-call-history?noredirect=1#comment50032872_31002583
