### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by NishantSolanki** [lampaa/com.lampa.startapp#17]
I have installed this plugin,

I also have checked in cordova CLI using  `cordova plugin is` command and this plugin is showing in the list.
But getting below error

`Uncaught TypeError: Cannot read property 'start' of undefined`

**Comment by lampaa** [comment]
Hi, @NishantSolanki!

Check variable ```javascriptnavigator.startApp``` on define.

**Comment by NishantSolanki** [comment]
How to check it?
I will appreciate if you can show any example??

**Comment by lampaa** [comment]
@NishantSolanki hmm, i used http://jsconsole.com/remote-debugging.html for remote debugging.

**Comment by NishantSolanki** [comment]
@lampaa 
Thanks its a great tool, but for this problem its returning `Script error`, not able to find the issue

**Comment by NishantSolanki** [comment]
Hey, It worked when I tried building an APK and then tested.
Thanks :)

How can I open playstore for a particular app download?

**Comment by lampaa** [comment]
@NishantSolanki 
try this:
```javascript
navigator.startApp.start([["action", "VIEW"], ["market://details?id=" + appPackageName"]], ...);
```

**Comment by janet-d** [comment]
Hello!
I have the same issue - and no solution yet. I think in my case it could have something to do with the plugin.xml and the <merge>-tag. Can you say, why you didn't use the <clobbers>-tag?
Cheers!

**Comment by janet-d** [comment]
Edit: It works. :) 
I guess I did not installed the plugin correctly.

**Comment by lampaa** [comment]
@janet-d hi!
I don't use "clobbers" tag because i don't know about it)

**Comment by AparnaMylavarapu** [comment]
Hi,

I am getting an error saying navigator.startApp is **undefined**.I have downloaded the plugin and version of plugin is 0.1.4..cordova version is 6.3.1.I am using ionic version 1.7.16.

**Comment by lampaa** [comment]
Hi!
remove `navigator` from line: `navigator.startApp`, example:
```javascript
var sApp = startApp.set(...);
sApp.start(successCb, failCb);
```

**Comment by AparnaMylavarapu** [comment]
Hi,
`startApp.set({
          "action":"ACTION_MAIN",
           "package":"com.ionicframework.DirMapLatLon",
            "application":"com.ionicframework.DirMapLatLon",
             "flags": ["FLAG_ACTIVITY_NEW_TASK"]
      }).start();`

I have used the above code to open the Application,but a blank page is opening.

**Comment by lampaa** [comment]
Hi, @AparnaMylavarapu!

Test this:
```js
startApp.set({
    "application":"com.ionicframework.DirMapLatLon"
}).start();
```

**Comment by AparnaMylavarapu** [comment]
Hi,

Sorry for late reply...I have applied the above code,but still the same issue.The application is opening but blank page

**Comment by AparnaMylavarapu** [comment]
I have clean the build and run the project and its working fine.
Thank you for your help.

**Comment by slowkazak** [comment]
anyone can help me with ionic2 and startapp?
