### ISSUE TITLE
Unable to pass the parameters when starting the app

### ISSUE THREAD

**Issue by ankeetasingh** [lampaa/com.lampa.startapp#20]
I got the following code to check app and start the app if available. I am able to open the app but the parameters aren't passed. Am I missing something here?
```js
navigator.startApp.check(appURL, function(message){
    // success checking
    console.log("The app is available in your Android device. Response Message: " + message + "!!");
    navigator.startApp.start([appURL, [
        {"store_name" : store_name},
        {"store_number" : store_id},
        {"state" : state},
        {"city" : city}
    ]], function(message){
        // Success starting
        console.log("Opening app on your Android device. Message: " + message);
    }, function(error){
        console.error("Unable to open the app on your Android device. Message: " + error);
    });
},
function (error) {
    console.error("The app is not available in your Android device!!! Message : " + error);
});
```

**Comment by lampaa** [comment]
Hi, @ankeetasingh!

Today I will decide this issue.

**Comment by ankeetasingh** [comment]
Hello @lampaa !

Any update on this issue?

**Comment by lampaa** [comment]
Hi, @ankeetasingh 

I testing plugin with extra fields, and I have the extra field in app launched through Startapp.
I install this: https://github.com/Initsogar/cordova-webintent
And add to `deviceready` this code:
```js
var appURL = 'com.phonegap.helloworld';
		
window.plugins.webintent.hasExtra("store_name", function(has) {
	if(!has) {
		navigator.startApp.check(appURL, function(message){
			// success checking
			console.log("The app is available in your Android device. Response Message: " + message + "!!");
			navigator.startApp.start([appURL, [
				{"store_name" : '100'},
				{"store_number" : '1'},
				{"state" : '111111'},
				{"city" : '22222'}
			]], function(message){
				// Success starting
				console.log("Opening app on your Android device. Message: " + message);
			}, function(error){
				console.error("Unable to open the app on your Android device. Message: " + error);
			});
		},
		function (error) {
			console.error("The app is not available in your Android device!!! Message : " + error);
		});	
	}
	else {
		window.plugins.webintent.getExtra("store_name", function(url) {
			alert(url);
		}, function() {
			// There was no extra supplied.
		});
	}
	alert(has);
	
}, function() {
	
});
```

**Comment by ankeetasingh** [comment]
Hello @lampaa!
 I am able to start the app but the parameters are not being passed into the app.

**Comment by lampaa** [comment]
@ankeetasingh what is the application you are running?

**Comment by ankeetasingh** [comment]
It's the inhouse app for my company.

I was able to open the and passed the param just using the webintent plugin
var appURL = "com.phonegap.helloworld://?store_name=ABC&store_number=123&state=NY&city=NYC";
window.plugins.webintent.startActivity({
    action: window.plugins.webintent.ACTION_VIEW,
    url: appURL},
    function() {console.log("Successfully opened the app")},
    function() {console.log('Failed to open URL via Android Intent')}
);

Thank you so much for your help!

**Comment by lampaa** [comment]
@ankeetasingh  hmm, a very interesting start. I have never seen this. Thanks!
