### ISSUE TITLE
How can I get the parameters

### ISSUE THREAD

**Issue by ryantchen** [lampaa/com.lampa.startapp#21]
Dear, 

I have two cordova apps BMIapp and receiveApp. I want to pass the parameters form BMIapp to receiveAPP.
Using the navigator.startApp.start and took a parameter, it can be launched the receiveAPP.
I just wrote code in BMIapp, as below:

navigator.startApp.start([
        ["com.android.receiveApp", "com.android.receiveApp.MainActivity"],
        [{"product_id":"100"}]
    ], function (message) {
        console.log("Launch App Success: " + message);
    }, function (error) {
        console.log("Launch App Error: "+ error);
    });

But, I don't know that how can I get the parameters in receiveApp. Am I write something in receiveApp to get the param ??

Ryant

**Comment by lampaa** [comment]
@ryantchen  you need to get the params in the receiveApp?
Use this plugin: https://github.com/Initsogar/cordova-webintent
getExtra

**Comment by ryantchen** [comment]
Yes, I need receiveApp to get the params. Does the webintent only using in Android?

**Comment by lampaa** [comment]
@ryantchen i write plugins only for android. For other systems, I do not know plugins.

**Comment by ryantchen** [comment]
@lampaa Thank your help.
