### ISSUE TITLE
iOS 9 issue

### ISSUE THREAD

**Issue by EduardoNE** [lampaa/com.lampa.startapp#23]
```javascript      
  if(device.platform === 'iOS') {
            scheme = 'instagram://';
        }
        else if(device.platform === 'Android') {
            scheme = 'com.instagram.android';
        }
navigator.startApp.start(scheme, function(message) {  /* success */
                            console.log(message); // => OK
                        }, 
                        function(error) {  /* error */
                            console.log(error);
                        });
```

still getting error after update for iOS9

i did a test, before the update works fine, after get only error.

**Comment by lampaa** [comment]
Hi, @EduardoNE!

Sorry, but code for iOS I'm not writing and therefore i dont know what could be the problem.

**Comment by EduardoNE** [comment]
Sorry for the late answer, i found the solution.
On the iOS9 has to put this in  <project name>-Info.plist file(on that case, to call the instagram):

<key>LSApplicationQueriesSchemes</key>
    <array>
      <string>instagram</string>
    </array>

Thanks!
