### ISSUE TITLE
Phonegap and startapp

### ISSUE THREAD

**Issue by Daniel-Frid** [lampaa/com.lampa.startapp#24]
Hi.
Is it possible to run startapp with Phonegap 5.3.6?
I get  "TypeError: Cannot read property 'check' of undefined"
Same goes for for "start"

The plugin seems to be installed. "com.lampa.startapp 0.0.4 "startApp""" when listing installed plugins.

Thanks.
/D

**Comment by lampaa** [comment]
Hi, @Daniel-Frid!

Apparently the new version phonegap again something has changed.

Try changing in `startApp.js` this:
```js
var exec = require('cordova/exec');

module.exports = {
```
to 
```js
navigator.startApp = {
```

AND 
```js
exec(...
```
to 
```js
cordova.exec(...
```

**Comment by Daniel-Frid** [comment]
Hi again.
Sorry for the late feedback.

It didn't do any better with those changes.
It's like it can't access the startApp.js. If I put a var in startApp.js and try to log it it'll be "undefined".

**Comment by CarsonChen1129** [comment]
I got the same "undefined" issue with Cordova 5.5 and 6.0, and the issue stays after making those changes. Does anyone have any solution on this case? Thank you very much in advanced.

**Comment by CarsonChen1129** [comment]
I was struggling with this issue but I then find out this plugin only works when you build your application and install it on your device as an application. It is not working in some environments like Ionic View. (Hope my experience helps)

**Comment by lampaa** [comment]
@CarsonChen1129, @Daniel-Frid  Hi! I update my cordova to last version and I tried to install plugin. Plugin has been installed and running without any changes. Please, check your code for errors.
