### ISSUE TITLE
Message to propose to install the external app

### ISSUE THREAD

**Issue by maxlinux2000** [lampaa/com.lampa.startapp#27]
Hi, 
actually my app run corretly whan I press a button that lauch an external app (bambuser) with the following code:
`<a href="#" class="btn" onclick='navigator.startApp.start("com.bambuser.broadcaster");'>Bambuser</a>`
But if bambuser is not installed, nothing occurs.

I want to have a message alert that advise the user that the bambuser is not installed, and pressing the button, open the playstore url in order to install the missing app at https://play.google.com/store/apps/details?id=com.bambuser.broadcaster&hl=en

It's possible that with your plugin?

MaX

**Comment by lampaa** [comment]
Hi, @maxlinux2000!

Check  com.bambuser.broadcaster for installed:
```javascript
navigator.startApp.check("com.bambuser.broadcaster", function(message) {  navigator.startApp.start("com.bambuser.broadcaster"); },  function(error) { alert('app not installed'); });
```

**Comment by maxlinux2000** [comment]
Hi Tnx! :)

I have modified a bit the examples in order to open the playstore after the alert box message:

<script>
    function launchbambuser() {
    var scheme;
    if (device.platform === 'iOS') {
        scheme = 'skype://';
    } else if (device.platform === 'Android') {
//        scheme = 'com.skype.raider';
        scheme = 'com.bambuser.broadcaster';
    } else if (device.platform === 'wp') {
        scheme = 'skype:';
    } else if (device.platform === 'windows8') {
        scheme = 'skype:';
    }
    navigator.startApp.check(scheme, function(message) { /* success */
        navigator.startApp.start(scheme, function(message) {
        }, function(error) { /* error */
            alert("I can't run bambuser");
        });
    }, function(error) {
        alert("Bambuser is not installed. Now we go to playstore.");
        window.open("https://play.google.com/store/apps/details?id=com.bambuser.broadcaster");
    });
} 
</script>     
<a href="#" onclick='launchbambuser();'>Bambuser</a></p>

**Comment by lampaa** [comment]
@maxlinux2000 Hi!
I'm glad you did it! I close question.
