### ISSUE TITLE
PG to PG application launch

### ISSUE THREAD

**Issue by murliatdure** [lampaa/com.lampa.startapp#29]
Able to launch the another phonegap application form phonegap application..

Can you please assist how to pass the parameters to the target PG app?
Given examples for the Intent are fine say - VIEW 98XXXX, CALL 98XXXX

Would like to some parameters and will navigate/execute something in target phonegap application.

**Comment by lampaa** [comment]
Hi, @murliatdure!

At the moment, the plugin can only send extra data: 
```javascript
navigator.startApp.start([["com.package", "com.package.SomeActivity"], [{"key1":"value1"},{"key2":"value2"}]], function(message) { /* success */
    console.log(message); // => OK
}, 
function(error) { /* error */
    console.log(error);
});
```
I recommend using plugin https://github.com/Initsogar/cordova-webintent to get extra data.
View issue: https://github.com/lampaa/com.lampa.startapp/issues/20
And my enhancement issue: https://github.com/lampaa/com.lampa.startapp/issues/22

**Comment by murliatdure** [comment]
web-intent is available only for the Android!!
Looking for the android, ios and win for the same.

**Comment by lampaa** [comment]
Hi, @murliatdure.
I develop plugin only for android.
