### ISSUE TITLE
Install via Phonegap Build?

### ISSUE THREAD

**Issue by thedouglenz** [lampaa/com.lampa.startapp#32]
This is searchable on the npm registry but including it in the config.xml file doesn't seem to be enough to build my app on PGB with this plugin included. Ideally I would add a line like the following to `config.xml`:

```
<plugin name="com.lampa.startapp" version="0.0.6" />
```

Any suggestions?

**Comment by webbpage** [comment]
Same issue here....

**Comment by lampaa** [comment]
Hi, @webbpage 
I do not understand what it is about, what you want to get in the end?

**Comment by webbpage** [comment]
I was able to fix this by adding the source property in the context.xml. Works for both 0.0.6 and 0.0.7

<gap:plugin name="com.lampa.startapp" version="0.0.6" source="npm" />

**Comment by lampaa** [comment]
Problem solved?

**Comment by webbpage** [comment]
Yes. PGB includes this plugin via a proper config.xml
