### ISSUE TITLE
Receiving Data's 

### ISSUE THREAD

**Issue by Gobinathsekar** [lampaa/com.lampa.startapp#34]
in ionic i want to send some text to print on android. how to receive that text on android app on specific activity

**Comment by lampaa** [comment]
Hi, @Gobinathsekar! 
You need to transfer data at a specific activity?
Try this:
```javascript
navigator.startApp.start(["com.app.name", [{"key1":"value1"},{"key2":"value2"}, {...}, {"keyN":"valueN"}]], function(message) { /* success */
    console.log(message); // => OK
}, 
function(error) { /* error */
    console.log(error);
});
```

**Comment by Gobinathsekar** [comment]
Hi @lampaa !
   Where and how to assign that key and value.. plz give me one sample from ionic and android

**Comment by lampaa** [comment]
Hi, @Gobinathsekar 

launch other application from you application:

```javascript
$scope.printer = function () {
	alert("printer");
	navigator.startApp.start([
		["com.example.possdkforandroid","com.example.possdkforandroid.PrintTextActivity"],
		[{ "Text_data","helo"}]
	], 
	function (message) { /* success */
		alert(" navigator called");
		alert(message);
	},
	function (error) { /* error */
		console.log(error);
		alert(error);
	});
}
```
In other application you must install plugin https://github.com/Initsogar/cordova-webintent and try this code:
window.plugins.webintent.getExtra("Text_data",
    function(url) {
        // url is the value of EXTRA_TEXT
    }, function() {
        // There was no extra supplied.
    }
);

**Comment by lampaa** [comment]
and this plugin to phonegap, but not for Ionic. My code examples may not work!

**Comment by Gobinathsekar** [comment]
in android how to add this https://github.com/Initsogar/cordova-webintent  plugin?

**Comment by lampaa** [comment]
@Gobinathsekar 
please, read docs: 
`cordova plugin add https://github.com/Initsogar/cordova-webintent.git`
