### ISSUE TITLE
Install Plugin Error

### ISSUE THREAD

**Issue by airas** [lampaa/com.lampa.startapp#36]
When I tried to 
Install: cordova plugin add com.lampa.startapp
Install: cordova plugin add https://github.com/lampaa/com.lampa.startapp.git

I get error 
Fetching plugin "com.lampa.startapp" via npm
Error: Failed to fetch plugin com.lampa.startapp via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.lampa.startapp

**Comment by lampaa** [comment]
Hi, @airas!
Hmm, I soon fix that.

**Comment by jmatsushita** [comment]
Hi there, just wanted to say I've ran into the same problem. Would be great to have a fix!

**Comment by esol1** [comment]
Same here.  I've been using this plugin for quite a while and it's been great.  I started a new project today with the 6.0.0 version of the CLI and now I'm seeing this error.

**Comment by airas** [comment]
hi friends I found a solution which is you have to add plugin like that
cordova plugin add cordova-plugin-startapp

have a good day

**Comment by lampaa** [comment]
Indeed, for some reason, now, instead of points npmjs used dashes.

**Comment by lampaa** [comment]
fixed: https://www.npmjs.com/package/com.lampa.startapp
