### ISSUE TITLE
TypeError when calling trying to call plugin methods

### ISSUE THREAD

**Issue by culer** [lampaa/com.lampa.startapp#37]
Hi,
When trying to call navigator.startApp.check(...) I get the following error:
TypeError: Cannot read property 'check' of undefined

When debugging, I found out that startApp isn't resolved.
However, a week ago it still worked and I have no idea what might have changed since then.

Any ideas on that?

Regards,
Colin

**Comment by lampaa** [comment]
Hi, @culer.
phonegap verion?

**Comment by culer** [comment]
Hi,
my current version is 5.3.3

**Comment by lampaa** [comment]
@culer, check `cordova_plugins.js` in `assets/www/` on:
```javascript
{
    "file": "plugins/com.lampa.startapp/www/startApp.js",
    "id": "com.lampa.startapp.startapp",
    "merges": [
        "navigator.startApp"
    ]
}
```
Next check files for exist:
```
assets/www/plugins/com.lampa.startapp/www/startApp.js
src/com/lampa/startapp/startApp.java
```
If they are missing, reinstall the plugin.
