### ISSUE TITLE
Plugin only works when installing from git

### ISSUE THREAD

**Issue by Habared** [lampaa/com.lampa.startapp#38]
`cordova plugin add com.lampa.startapp`
installs version 0.0.7 that doesn't work (navigator.startApp is an empty object)

`cordova plugin add https://github.com/lampaa/com.lampa.startapp.git`
gets version 0.0.6 that work as expected

tried on cordova 6.0.0 and android platform 5.1.1

**Comment by lampaa** [comment]
Hi, @Habared.
I'll check and corrected.

**Comment by lampaa** [comment]
@Habared hi!
I updated plugin to new version. Problem was solved.
