### ISSUE TITLE
StartApp plugin is not registred on Phonegap repository

### ISSUE THREAD

**Issue by vitorsgomes** [lampaa/com.lampa.startapp#4]
Hi, I'm trying to build a phonegap application that uses Statapp to call another application but when I try to build it from https://build.phonegap.com/apps I got the error message "plugin unsupported: org.apache.cordova.startapp @ 0.3.0".

I guess it happens because your plugin is not registred in Phonegap 3rd party plugins, any thoughts if and when will you register it?

Thanks.

**Comment by kraihn** [comment]
Can you register this plugin with the [Cordova Plugin Registry](http://plugins.cordova.io/#/)?

**Comment by lampaa** [comment]
@kraihn no, at the moment I have some problems: https://github.com/lampaa/org.apache.cordova.startapp/issues/4#issuecomment-61080766

**Comment by kraihn** [comment]
@lampaa , [#4 (comment)](https://github.com/lampaa/org.apache.cordova.startapp/issues/4#issuecomment-61080766) isn't an issue in the [Cordova Plugin Registry](http://plugins.cordova.io/#/). They operate independently from Adobe (and PhoneGap). It's an open source registry run by the Apache organization. You only need an email address to register and publish plugins for free.

**Comment by lampaa** [comment]
@kraihn http://plugins.cordova.io/#/package/com.lampa.startapp
