### ISSUE TITLE
cordova.define being imported twice.

### ISSUE THREAD

**Issue by jamieowen** [lampaa/com.lampa.startapp#40]
Hi,

Cheers for all your work on this plugin!
I've noticed an error on my project with recent updates.=

Cordova seems to be importing/defining the module twice.
The resulting startApp.js plugin in the platforms has the first 2 lines

```
cordova.define("com.lampa.startapp.startapp", function(require, exports, module) {
cordova.define("com.lampa.startapp.startApp", function(require, exports, module) {
```

In my source plugins folder the startApp.js already contains the cordova.define statement.
Which cordova is then adding again.. 
There is no [startApp.manually.js](https://github.com/lampaa/com.lampa.startapp/blob/master/www/startApp.manually.js) file either - But it seems like this is the one being imported from the plugin manager.

Any ideas?

Cheers,

Jamie

**Comment by lampaa** [comment]
Hi, @jamieowen!
This bug fixed in new version. I did not realize that cordova wrap script during installation.
Script startApp.manually.js need for manual install.

Delete and reinstall plugin.
