### ISSUE TITLE
Missing release 0.0.6

### ISSUE THREAD

**Issue by faenschi** [lampaa/com.lampa.startapp#41]
hello

where can I find older releases like 0.0.6? somehow they are missing in github?
https://github.com/lampaa/com.lampa.startapp/releases
 we have several problems (especially when opening a link in a browser) with the new release so we would like to use version 0.0.6.

regards
angela

**Comment by lampaa** [comment]
Angela, hello!
Let me help you create a script for the new version of the plugin?

**Comment by faenschi** [comment]
Hi Lampaa
Can you tell me why there are no older relases than 0.1.4? How can i get the version 0.0.6 ?
Or maybe you can tell me how i can open a link in a browser with your new version? i had no problems doing that with version 0.0.6.

regards angela

**Comment by lampaa** [comment]
Hi, @faenschi!

Test this:
```js
startApp.set({ /* params */
    "action": "ACTION_VIEW",
    "uri": "https://github.com/lampaa"
}).start();
```
