### ISSUE TITLE
Uber Example

### ISSUE THREAD

**Issue by Rex90** [lampaa/com.lampa.startapp#43]
Hi - thanks for your efforts on this it looks great. 

Can you please provide an example for how to launch the Uber app with deep linking to ride requests and optional parameters? This seems straightforward for iOS but I can't figure out what the options for android need to be.

https://developer.uber.com/docs/deep-linking

**Comment by lampaa** [comment]
@armensg hi!
Test this:

```javascript
startApp.set({ /* params */
    "action": "ACTION_VIEW",
    "uri": "uber://?action=setPickup&pickup=my_location&client_id=YOUR_CLIENT_ID"
}).start();
```

**Comment by armensg** [comment]
Thanks! I'm actually trying to use this with an ionic/Cordova app and having trouble figuring out how to install it :(

**Comment by armensg** [comment]
After doing Cordova plugin install do I need to include any JavaScript scripts on my index.html?

**Comment by armensg** [comment]
This is how im trying to use it in a more angular fashion

`
// link     :     https://github.com/lampaa/com.lampa.startapp
.factory('$startApp', ['$window', function ($window) {
    'use strict';

    var sApp;
    return {
        set: function(params, extras){
            if($window.plugins.startApp){
                sApp = $window.plugins.startApp.set(params, extras);
            }else{console.error("startApp plugin was not found on window.");}
        },
        check: function(params, extras, successCallback, errorCallback){
            if($window.plugins.startApp){
                $window.plugins.startApp.set(params, extras).check(successCallback, errorCallback);
            }
        },
        start: function(params, extras, successCallback, errorCallback){
            if($window.plugins.startApp){
                $window.plugins.startApp.set(params, extras).start(successCallback, errorCallback);
            }
        }
    };

}])`

**Comment by lampaa** [comment]
Hi, @armensg. 
method set() return methods start() and check():
```javascript
app.factory('startAppFactory', ($window) {
    'use strict';

    return $window.plugins.startApp;
}
//use:
app.service('Service', function(MathService){
    this.sApp = startAppFactory.set(...);
});
```

**Comment by rolinger** [comment]
I got deeplinks to work using the method you posted above for Uber:

Method 1: works!
```
startApp.set({ /* params */
    "action": "ACTION_VIEW",
    "uri": "uber://?action=setPickup&pickup=my_location&client_id=YOUR_CLIENT_ID"
}).start();
```

...but is there a way to do it using the uri parameters as extra key/value like in method 2 below: 

Method 2: doesn't work
```
startApp.set({
   "action" : "ACTION_VIEW",
   "uri" : "uber://"
}, {
   "action" :  "setPickup",
   "pickup" :  my_location",
   "client_id" : YOUR_CLIENT_ID
}
```

The first method, that is working, forces me to create several different methods versus a universal (method 2) approach.  Same question/issue applies for standardizing the calls for iOS too.

**Comment by lampaa** [comment]
Hi, @rolinger!

https://developer.uber.com/docs/riders/ride-requests/tutorials/deep-links/introduction
Parameters can be passed only through the Uri scheme.
