### ISSUE TITLE
Set a new Alarm Clock

### ISSUE THREAD

**Issue by Danyzzz** [lampaa/com.lampa.startapp#45]
Hi guys,
it is possible set a new alarm clock like this?
http://stackoverflow.com/questions/8664670/how-to-launch-alarm-clock-screen-using-intent-in-android

I tried but when pressed button there is an error "NoSuchFieldException: ACTION_SET_ALARM"

This is my code example:

```
      var sApp = startApp.set({ /* params */
          "action":"ACTION_SET_ALARM",
          "intentstart":"startActivity",
      }, { /* extras */
          "EXTRA_MESSAGE":"Nuova sveglia Deneb",
          "EXTRA_HOUR":"12",
          "EXTRA_MINUTES":"00"
      });

      sApp.start(function() { /* success */
          console.log("OK");
      }, function(error) { /* fail */
          alert(error);
      });
```

**Comment by lampaa** [comment]
@Danyzzz hi! At the moment this is not possible, but I'll try to add it as soon as possible.

**Comment by Danyzzz** [comment]
Thanks @lampaa !!! I think this feature is interesting to use :)

**Comment by Danyzzz** [comment]
Hi @lampaa,
There are news? with latest update not working yet...

Thanks a lot.

**Comment by lampaa** [comment]
```
var sApp = startApp.set({ /* params */
    "action":"android.intent.action.SET_ALARM",
    "noParseAction": true
}, {
    "android.intent.extra.alarm.MESSAGE":"New Alarm",
    "android.intent.extra.alarm.HOUR":17,
    "android.intent.extra.alarm.MINUTES": 30
});

sApp.start(function(success) {
    console.log(success);
}, function(error) {
    console.error(success);
});
```

and add to AndroidManifest.xml:

`<uses-permission android:name="com.android.alarm.permission.SET_ALARM"/>`

plugin version: 6.1
