### ISSUE TITLE
Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by ofcapl** [lampaa/com.lampa.startapp#47]
Hello,
I'm writing an app which launch other apps (games) from it - here's my code:

```
        var app = navigator.startApp.set({
            "package": "com.ea.game.nfs14_row"
        });
        app.start(function(){
            console.log('Game started!');
        }, function(err){
            console.log('Game start failed! ', err);
        });
```

It's activated on click event via button, but when I click I'm getting an error:

`Uncaught TypeError: Cannot read property 'set' of undefined`

Earlier, I was trying to use `startApp` without `navigator` but that raises me an error that `startApp is not defined`. 

I'm using Intel XDK and I've added plugin via it's window plugin tool by pasting github url - I think it is installed correctly.

Please help!

**Comment by lampaa** [comment]
Hi, @ofcapl. Remove "navigator" from code:

var app = startApp.set({
            "package": "com.ea.game.nfs14_row"
        });
        app.start(function(){
            console.log('Game started!');
        }, function(err){
            console.log('Game start failed! ', err);
        });

**Comment by ofcapl** [comment]
@lampaa thank! This time it worked! I think it doesn't work before because Intel XDK not installed additional debugger for this plugin yet.

**Comment by lampaa** [comment]
@ofcapl ok, thanks!

**Comment by marwanyousry** [comment]
Hello, 
i have installed com.lampaa.startapp plugin in my phonegap project and when i tired  to check if plugin is defined or not by this code 
            navigator.startApp.extraFields(function(fields) { /* success */
				    console.log(fields);
				}, function() { /* fail */

				});

i got error : Cannot read property 'extraFields' of undefined also if i used 'set' method  please @lampaa @lukaszkups any advise ?

**Comment by lampaa** [comment]
Hi, @marwanyousry!

test this:
```
startApp.extraFields(function(fields) { /* success */
    console.log(fields);
}, function() { /* fail */

});
```

**Comment by marwanyousry** [comment]
@lampaa 

i got an error :  Uncaught ReferenceError: startApp is not defined.

and when i tried to install plugin in my phonegap project by this command 
                   cordova plugin add com.lampa.startapp
Plugin "com.lampa.startapp" already installed on android.

**Comment by lampaa** [comment]
@marwanyousry hmm, view assets/www/cordova_plugins.js

You see this code?
```
{
    "file": "plugins/com.lampa.startapp/www/startApp.js",
    "id": "com.lampa.startapp",
    "merges": [
        "startApp"
    ]
}
```

**Comment by marwanyousry** [comment]
@lampaa 
yes this code exists in ../assets/www/cordova_plugins.js

**Comment by lampaa** [comment]
@marwanyousry you call the code after deviceready?
Tried to remove and install the plugin again?

**Comment by marwanyousry** [comment]
yes i tried to remove then install plugin again and yes in inti method i put this line 

document.addEventListener("deviceready", onDeviceReady, false);

and in onDeviceReady function 

function onDeviceReady() {
		
		navigator.startApp.getExtra(field, function(value) {
			    console.log(fields);
			}, function() { 

			});
        
    }

got same error

**Comment by marwanyousry** [comment]
@lampaa any advise ?

**Comment by lampaa** [comment]
No need to use a variable `navigator`.

```
document.addEventListener("deviceready", function() {

	startApp.extraFields(function(fields) { /* success */
		console.log(fields);
	}, function(fail) { /* fail */
		alert(fail);
	});
	
	var field = "extra_field";

	startApp.getExtra(field, function(value) {
		console.log(value);
	}, function(fail) { 
		alert(fail);
	});
}, false);
```
More I do not know how to help. If does not work, try another plugin.
