### ISSUE TITLE
Issue opening Uber in iOS 9.3

### ISSUE THREAD

**Issue by fabstao** [lampaa/com.lampa.startapp#49]
Hi!

First, thanks a lot for this plugin!

I have Cordova 6.1, latest Xcode, and when I try:

``` javascript
startApp.set("uber://").start();
```

I get the follwing error:

> 2733:1906788] -canOpenURL: failed for URL: "uber://" - error: "This app is not allowed to query for scheme uber"

How do I apply for permissions?

Thanks a lot!!

**Comment by ramogundogdu** [comment]
I can't also launch any apps on ios devices with this plugin. Why?

**Comment by lampaa** [comment]
Hi, @fabstao, @ramogundogdu!
Sorry guys, but a plugin for iOS, I did not write, and I can not help you.
@fabstao view this: http://learnsauce.com/knowledgebase/viewtopic.php?t=921

**Comment by kuroiarashi** [comment]
You need to whitelist the url schemes in the info.plist file. The property name is LSApplicationQueriesSchemes.

**Comment by rolinger** [comment]
For iOS, can the startApp.set() ; take parameters? or extra key/value parameters?

```
startApp.set({ 
    "uri": "whatsapp://"
}, {
    "EXTRA_TEXT":"Text...",
    "chat": true
}).start();

```
???

**Comment by lampaa** [comment]
Hi, @rolinger!

view example:
```javascript
startApp.set({ /* params */
    "action": "ACTION_SEND",
    "package": "com.whatsapp",
    "type": "text/plain",
    "uri": "+79123456789"
}, {
    "EXTRA_TEXT":"Text...",
    "chat": true
}).start();
```

**Comment by lampaa** [comment]
Hi, @rolinger!
For IOS you can pass only one parameter: `startApp.set("whatsapp://");`
