### ISSUE TITLE
Start an external app with component [Shazam app]

### ISSUE THREAD

**Issue by Danyzzz** [lampaa/com.lampa.startapp#50]
Hi guys,
I would like start a class recognition for shazam app with this parameters:

```
var sApp = startApp.set({
    "component": ["com.shazam.android", "com.shazam.android.intent.actions.START_TAGGING"]
});
sApp.start(function() { /* success */
    console.log("OK");
}, function(error) { /* fail */
    alert(error);
});
```

But there is an error :( How I can resolve?

![img-20160507-wa0003](https://cloud.githubusercontent.com/assets/12005910/15091447/d2a638ae-1449-11e6-8f2b-c7e1ab990d82.jpg)

**Comment by lampaa** [comment]
Hi, @Danyzzz 
Hmm, I will correct it this weekend.

**Comment by Danyzzz** [comment]
Thanks @lampaa :+1:

**Comment by Danyzzz** [comment]
Hi, @lampaa 
There are news?

**Comment by lampaa** [comment]
Hi, @Danyzzz!
I fixed plugin. Update it from you pc and use this code:
```
var sApp = startApp.set({
	"intent": "com.shazam.android.intent.actions.START_TAGGING",
	"flags": ["FLAG_ACTIVITY_NEW_TASK"]
}); 
		
sApp.start(function() { /* success */
	console.log("OK");
	}, function(error) { /* fail */
	alert(error);
});
```

**Comment by Danyzzz** [comment]
Wow @lampaa, works perfectly!!!! thanks a lot :)
There are news for issue #45 ?

**Comment by MCRJ9808** [comment]
@lampaa 
hi, i want to use you plugin -> com.lampaa.startapp<- but i want to do that on typescript. it is posible.
