### ISSUE TITLE
Make directly a Skype Call

### ISSUE THREAD

**Issue by ramogundogdu** [lampaa/com.lampa.startapp#54]
How can I call directly a Skype contact? Like this: `skype:SkypeContact?call` How is the `"uri"`?

**Comment by Danyzzz** [comment]
You have tried this code?

`startApp.set({ /* params */
    "action": "ACTION_VIEW",
    "uri": "skype:+79109999999"
}).start();`

**Comment by ramogundogdu** [comment]
Thanks. It works...
