### ISSUE TITLE
app ios crash

### ISSUE THREAD

**Issue by jedofus** [lampaa/com.lampa.startapp#56]
Hello ,
i have a problem with function check on ios .
when i check if an app is existing for example map , it return true (it's work) 
but when an app is not exist in device , my app crash. 
how can i resolved it ?

**Comment by lampaa** [comment]
Hi, @jedofus!
Sorry, but I dont developed fo ios. 
I advise you to ask in the ios forum, and if you will fixed check function, please make a pull request.

**Comment by lampaa** [comment]
I just do not even have the device for testing.

**Comment by jedofus** [comment]
bug check function is crash app , just used start function on your app. start function also check if external app is available after open or not external app ;)
