### ISSUE TITLE
startApp is not defined.

### ISSUE THREAD

**Issue by vinodmishra-ssts** [lampaa/com.lampa.startapp#58]
i am using phonegap build plugin:

`< gap:plugin name="com.lampa.startapp" version="0.0.6" source="npm" />`

i have written the code :

```js
var sApp = startApp.set({
    "action": "ACTION_SEND",
    "package": "com.whatsapp",
    "type": "text/plain",
    "uri": "+918958312000"
}, {
    "EXTRA_TEXT": "Text...by vkm ",
    "chat": true
}).start();
```

showing error : startApp is not defined.

I am new in phonegap.. please help

**Comment by Danyzzz** [comment]
Hi!
If you use "start();" not needed use of "var sApp =".
You can write:

startApp.set({
"action": "ACTION_SEND",
"package": "com.whatsapp",
"type": "text/plain",
"uri": "+918958312000"
}, {
"EXTRA_TEXT":"Text...by vkm ",
"chat": true
}).start();

**Comment by vinodmishra-ssts** [comment]
Thank you, Problem is solved..

Vinod Kumar Mishra
Director
M/s Shaktisheel Technosoft Private Ltd
Mobile : 8958312000

**Comment by vinodmishra-ssts** [comment]
but could not success to send text to anyone. I shall be highly grateful, if you please guide me.
Error is not coming, only whatsapp is opening..

Regards
