### ISSUE TITLE
Question: How to use some url intent 

### ISSUE THREAD

**Issue by m4rky77** [lampaa/com.lampa.startapp#59]
Hi, 

I'm trying to use the plugin with this url, but i don't understand how use it.

the example that i try to make to it work with this:

`<a href="intent://scan/#Intent;scheme=zxing;package=com.google.zxing.client.android;S.browser_fallback_ul=http%3A%2F%2Fzxing.org;end"> Take a QR code </a>`

I don't know how to use the plugins to make the same call.

It is possible to do this with this plugin?

Thank you

**Comment by lampaa** [comment]
Hi!
Test this:
```js
startApp.set({
    "application":"com.google.zxing.client.android"
}).start();
```
