### ISSUE TITLE
May I inquire an example using Ionic 2?

### ISSUE THREAD

**Issue by CarsonChen1129** [lampaa/com.lampa.startapp#65]
Hi, I have been using this amazing plugin in my Ionic 2 application, right now I am developing an application using Ionic 2, which is Angular2+Typescript. I tried the same way of deploying this plugin in Ionic 2 app and the term "startApp" cannot be recognized. (Not found) May I ask how can I use this plugin in Ionic 2? Thank you very much.

**Comment by CarsonChen1129** [comment]
I found the solution. Just simply define the variable in the components and it will work. For example, add 
```
declare var startApp:any;
```
after the imports and everything else works like a charm. 

Sorry for asking such a silly question.

**Comment by wuilmerj24** [comment]
@CarsonChen1129 Hi, could you share the code?
