### ISSUE TITLE
startActivityForResult

### ISSUE THREAD

**Issue by lvcsistemas** [lampaa/com.lampa.startapp#66]
Hi I'm calling the intent like this:

        var sApp = startApp.set({
            "intentstart"   : "startActivityForResult",
            "component"  : ["com.checkout.app","com.checkout.app.Activity"]
        }, { 
            "value"             : "5",
            "payment"      : "moneyt"
        });

But how can I receive the result from the intent?

Thanks

**Comment by IsraelSistemas** [comment]
I hava the next code

` var sApp = startApp.set({ /* params */                                                                
                                "intentstart": "startActivity",                                
                                "component": ["com.company.appname", "com.company.appname.UILibrary.UsersViewActivity"]
                            }, { /* extras */
                                "PersonID": response.Participant1,
                                "ChatID": response.ChatID,
                                "PersonName": response.Name
                            });

                            sApp.start(function (response) {
                                console.log(response);
                            }, function (error) {
                                console.log(error);
                            });
                            break;`


But im receiving the next error: 

> Permission Denial: starting Intent { cmp=com.company.nameapp/.UILibrary.UsersViewActivity (has extras) } from ProcessRecord{3dbe38a7 11642:com.company.nameapp/u0a155} (pid=11642, uid=10155) not exported from uid 10154


Help please .

**Comment by lvcsistemas** [comment]
Hi Israel, look in your config.xml if you have something like this:

<access origin="*" />
  <access origin="tel:*" launch-external="yes" />
  <access origin="https://*" launch-external="yes" />
  <access origin="http://*" launch-external="yes" />

**Comment by IsraelSistemas** [comment]
Hi @lvcsistemas, I did not have that code lines (except access origin="*"), so, I put it inside my config.xml but I got the same result. Do you have any idea about this error?, Can you open an app in a specific view (for example a chat in whatsapp) with parameters?.

**Comment by lvcsistemas** [comment]
Hi Israel see if this could help you: [](http://stackoverflow.com/questions/4162447/android-java-lang-securityexception-permission-denial-start-intent)

**Comment by IsraelSistemas** [comment]
@lvcsistemas  I could start the app adding this line in the activity to I want to access "android:exported="true" in the manifest, but the chat in my case I want to access does not have any parameter I sent, so I checked with the function "startApp.getExtras()" and does not return any parameter that I have declared, do you know anything about this issue?.

**Comment by lvcsistemas** [comment]
I don't know if that's your case, but try to put more parameters like the package and go trying, I was trying to get the informations by .check and discovered that without the package the plugin returns nothing. Another thing you can do is look the file java of the plugin and have more knowledge about how it treats the callers.

**Comment by gilbertoss** [comment]
@lvcsistemas 
Were you able to create the callback listener for startActivityForResult?

**Comment by lampaa** [comment]
Hi, view: https://github.com/lampaa/com.lampa.startapp/issues/107
