### ISSUE TITLE
 'openURL:' is deprecated in iOS 10

### ISSUE THREAD

**Issue by dawiinci** [lampaa/com.lampa.startapp#69]
> /Plugins/com.lampa.startapp/startApp.m:30:38: 'openURL:' is deprecated: first deprecated in iOS 10.0 - Please use openURL:options:completionHandler: instead

I'm not sure if it doesn't work for me because of this or if I have another issue as well. I just want to open Apples reminder App. I included startApp.js and installed with this command:
`cordova plugin add com.lampa.startapp
`
 

```
var sApp = startApp.set("x-apple-reminder://");

    
sApp.start(function() { /* success */       
           alert("OK");
           }, function(error) { /* fail */
           alert(error);
           });
}
```

Thanks for your support.

**Comment by dawiinci** [comment]
I just added this code to my project but still not working:

`<allow-navigation href="x-apple-reminder://*/*" />
`in config.xml
 

> LSApplicationQueriesSchemes
> x-apple-reminder (as string)

in platforms/ios/<appname>/<appname>-Info.plist

**Comment by lampaa** [comment]
Hi, @dawiinci 

View that issue: https://github.com/lampaa/com.lampa.startapp/issues/49#issuecomment-218018421
