### ISSUE TITLE
Get Intent result

### ISSUE THREAD

**Issue by slowkazak** [lampaa/com.lampa.startapp#71]
I need start external app, get parameters and rea that.

My code returns only "Ok"
`      var sApp = startApp.set({
        "intent": "ru.toucan.GET_PARAMETERS",
        "package": "ru.toucan.merchant",
        "intentstart": "startActivityForResult",
      });

      sApp.start(function (response) {
        console.log(response);
      }, function (error) {
        console.log(error);
      });`
Also external app can retrieve only xml data.
[Api for external app ](https://github.com/smart-fin/AndroidApi/tree/master/V3/src/ru/toucan/api)

Anyone can help me?

**Comment by gilbertoss** [comment]
@slowkazak 
Were you able to create the callback listener for startActivityForResult?

**Comment by Smohanapriya** [comment]
Hi,
  Anyone find the solution for the above issue?? I am also the facing the same issue.

 And I am getting error "invalid intent" as a toast message while opening the app

**Comment by lampaa** [comment]
Hi, view: https://github.com/lampaa/com.lampa.startapp/issues/107
