### ISSUE TITLE
Run intent ad broadcast don't work

### ISSUE THREAD

**Issue by r1si** [lampaa/com.lampa.startapp#72]
Hi, 
I try your extension to run an intent as broadcast but don't work...
If I run with adb all works like a charm.

ADB commad: 
`am start -a com.llamalab.automate.intent.action.START_FLOW -d content://com.llamalab.automate.provider/flows/17/statements/1 `

code that i have wrote

```js
var cmd_to_run = startApp.set({ /* params */
    "package":"com.llamalab.automate",
    // "action":"intent.action.START_FLOW",
    // "intent":"com.llamalab.automate.intent.action.START_FLOW ",
    "intent":"intent.action.START_FLOW ",
    "uri": normalize_net_state,
    "intentstart":"sendBroadcast"
});

cmd_to_run.start(function() { /* success */
    console.debug("IT WORKS!");
}, function(error) { /* fail */
    console.error(error);
});
```

I have try all combination commented
but don't work :(

**Comment by lampaa** [comment]
Hi, @r1si 

I updated plugin, broadcasts now work. View examples in main page of plugin 🙏
