### ISSUE TITLE
hi i am using lampa.startapp i want to call native app 

### ISSUE THREAD

**Issue by tayyab3331** [lampaa/com.lampa.startapp#79]
public void sendDataToDefaultPrinter(String textoToSend)
                {
                Intent intentPrint = new Intent();
                intentPrint.setAction(Intent.ACTION_SEND);
                intentPrint.putExtra(Intent.EXTRA_TEXT, textoToSend);
                intentPrint.setType("text/plain");
                Log.i(internalClassName, "buttonPrintToDefaultPrinter Start Intent");
                this.startActivity(intentPrint);
                }
              

convert this thing to lampa.start app

**Comment by lampaa** [comment]
Hi!

```js
startApp.set({ /* params */
	"action": "ACTION_SEND",
	"type": "text/plain"
}, {
	"EXTRA_TEXT": "textoToSend"
}).start();
```
