### ISSUE TITLE
 Feature Suggestions

### ISSUE THREAD

**Issue by thanhphat11** [lampaa/com.lampa.startapp#81]
Dear all

I would like to have more features to automatically install apps from the Play Store and open it, controlling the install command from FCM? Please help me have a solution to this problem please

**Comment by lampaa** [comment]
You can only open the application page in google play:

```js
startApp.set({ /* params */
	"action": "ACTION_VIEW",
	"uri": "market://details?id=com.lampa.startapp"
}).start();
```
