### ISSUE TITLE
Not working on IOS

### ISSUE THREAD

**Issue by kvarinder** [lampaa/com.lampa.startapp#85]
HI,
i have used this plug-in for IOS application and here is my code

           var sApp = startApp.set("twitter://");
            sApp.check(function (values) { /* success */
                console.log(values);
            }, function (error) { /* fail */
                alert(error);
            });

This code always gives alert message with "False";
Please help !!

**Comment by Eclektic** [comment]
I have the same issue since one or two week (maybe more don't really know). Before, everything works fine, the plugin return the correct state for the asked app. 

I think an iOS update break the plugin compatibility. I keep investigate and come back to you if I found a solution.

**Comment by Eclektic** [comment]
OK I know why this is not working anymore. You have to declare the shemeUrl you want to test/open in the info.plist file. It can be found in "yourProject/platforms/ios/projectName/projectName-info.plist". 
You'll need to add this key: "LSApplicationQueriesSchemes" as an array and then add every shemeUrl you want to use in your app.

`<key>LSApplicationQueriesSchemes</key>
    <array>
     <string>sheme-url01</string>
     <string>sheme-url02</string>
    </array>
`
It will not work if you add "://" to your entry.

**Comment by kvarinder** [comment]
Thanks Eclektic,
i am working with build.phonegap, there is no plist file.
But i will try this in config.xml.

**Comment by kvarinder** [comment]
Hi issue has been resolved, Thanks Eclektic for your support
Here is my code

config.xml
===================================================
<platform name="ios">
    <config-file platform="ios" target="*-Info.plist" parent="LSApplicationQueriesSchemes">
        <array>
          <string>uber</string>
        </array>
    </config-file>
</platform>


button click event
=====================================================
 var sApp = startApp.set("uber://");
 sApp.start(function (values) {  
                console.log(values);
            }, function (error) {  
                alert(error);
            });
