### ISSUE TITLE
Cannot set uri and type

### ISSUE THREAD

**Issue by rhyst** [lampaa/com.lampa.startapp#92]
In my android project I am trying to get an external app to open a file (in the external cache) by executing this:

    startApp.set({
        "action": action,
	 "package": "some.package.name",
	 "type": "text/plain",
	 "uri": "file://some/file/path"
     }).start();

Results in the following logcat output

    ActivityManager: START u0 {act=android.intent.action.VIEW typ=null flg=0x10000000 cmp=ComponentInfo{some.package.name/some.component.name}} from uid 10293 on display 0

The 'typ' value is null for some reason.

If I execute the the same but without the uri:

    startApp.set({
        "action": action,
	 "package": "some.package.name",
	 "type": "text/plain",
     }).start();

Then the type does seem to be present:

    ActivityManager: START u0 {act=android.intent.action.VIEW typ=text/plain flg=0x10000000 cmp=ComponentInfo{some.package.name/some.component.name}} from uid 10293 on display 0

The app opens in both cases but does not open the file. From looking at other intent logs the app I am attempting to open the file with needs the type to be set in the intent. 

Have I misunderstood how to use the intents or is there something else wrong?

**Comment by lampaa** [comment]
Hi, @rhyst!
In android method `setType()` automatically clears any data that was previously set (for example by `setData(Uri)`) (via https://stackoverflow.com/questions/13719471/why-setdataandtype-for-an-android-intent-works-fine-when-setdata-and-settype)

To fix the situation, you need to slightly change the plugin code for your case:
replace https://github.com/lampaa/com.lampa.startapp/blob/master/src/android/startApp.java#L155
to: 
```java
LaunchIntent.setDataAndType(Uri.parse(params.getString("uri")),"text/plain");
```

**Comment by rhyst** [comment]
Sorry this has taken so long to close but yes that is what I ended up doing. Thank you for your help.
