### ISSUE TITLE
Open an app that is not famous.

### ISSUE THREAD

**Issue by ViniciusT** [lampaa/com.lampa.startapp#94]
I need to call an app called Prizor but he is never called, it always return an error and i'm calling the same way as twitter and twitter works. I'm using prizor:// but it can not be found.

**Comment by gregor-srdic** [comment]
I believe you should be using target app package name
var sApp = startApp.set({
	"application":"com.prizor"
});

For custom urls to work, target app needs to register them with the OS (iOS or android) - that can be done using deeplinks or custom url plugins
