### ISSUE TITLE
Array converting to String while passing in extras

### ISSUE THREAD

**Issue by pranayrahulios** [lampaa/com.lampa.startapp#95]
Hi @lampaa 

```js
window.startApp.set({
'intent': 'com.**************',
 'uri': 'locate:'
}, { upcs : ["123445","12334646"] }).start(function () {
```

But upcs (extras) is sending while navigating from Hybrid app to native Android app as STRING instead of ARRAY
"upcs" : "["123445","12334646"]"
Array is converted to string, could you please resolve this issue ASAP

**Comment by lampaa** [comment]
At the moment, such support is not foreseen.
