### ISSUE TITLE
How to share data from my app to another app

### ISSUE THREAD

**Issue by manaswinid14** [lampaa/com.lampa.startapp#99]
Hi,
I am able to call another application from my application. But how can I send share data between two apps.
Kindly suggest..

**Comment by lampaa** [comment]
Hi!

Using extras data:

```js
var sApp = startApp.set({ /* params */
    ...
}, { /* extras */
    "EXTRA_STREAM":"extraValue1",
    "extraKey2":100500
});
```

**Comment by sandyrana** [comment]
hi @lampaa 
Please help having same issue with me marked above.
